### PR TITLE
Dw/rpc flag handler

### LINKED ISSUE #737: bug: rpc vs rpc-config and public nodes
**Describe the bug**

If `--rpc` is not passed, we default to publicnode, but we don't require --rpc to be passed after the first time -- not to mentioned `--rpc-config`.

We should always use a non-default RPC if we have it

https://github.com/hyperware-ai/hyperdrive/blob/bd9e5bd5a51a521fff434727c63fcaee525c27d9/hyperdrive/src/main.rs#L275
https://github.com/hyperware-ai/hyperdrive/blob/36f10c40da371656992e32d9bac97fdc9234c717/hyperdrive/src/register.rs#L42
https://github.com/hyperware-ai/hyperdrive/blob/36f10c40da371656992e32d9bac97fdc9234c717/hyperdrive/src/register.rs#L250-L255

### PR DESCRIPTION
**Pull request by dolled-possum**
## Problem

inconsistent handling of --rpc vs --rpc-config flags

## Solution

The handling of these flags has now been rationalized (and also made consistent with runtime handling as well). We start by recognizing that --rpc is just a special case (one provider, no auth) of what can be specified in --rpc-config. So only one or the other should be specified (if any), not both.

eth_provider_config will be potentially modified by these flags, adding ProviderConfigs at the top of the vector (after deduplicating them if needed), and preserving the order if multiple ProviderConfigs are specified in the --rpc-config file.

The calls to serve_register_fe and login_with_password now accept this whole eth_provider_config, not merely an RPC URL string. This propagates as required, eventually calling the new function connect_to_provider_from_config, which replaces the previous connect_to_provider function. Now it is possible for an authenticated connection to serve register and login with password. It will also attempt to use all of the saved/configured RPC providers, only falling back to the default if no others succeed.

## Notes

I'll remove tagged debug logging before merging

### CODE REVIEW

File: hyperdrive/src/main.rs [hunk 1]
```diff
@@ -129,38 +134,114 @@ async fn main() {
...
-                    provider: lib::eth::NodeOrRpcUrl::RpcUrl { url, auth },
-                },
-            );
+        // TODO: Remove debug logging before merging
+        eprintln!(
+            "[DEBUG-AUTH] Processing --rpc-config flag with file: {}",
+            rpc_config.display()
+        );
+
+        match std::fs::read_to_string(&rpc_config) {
```
Comment (nick1udwig) [inline hyperdrive/src/main.rs:170]: `match` is a great construct, but style-wise it should be used sparingly when other control flow is available because of the double-indentation it causes. Especially when there are two main outcomes we care about, we have two good alternatives:

alternative 1:

```rust
if let Ok(contents) = std::fs::read_to_string(&rpc_config) {
    ...
}
...
```

or (if we care about the non-Ok case, but don't need to unpack it)

```rust
if let Ok(...) ... {
} else {
}
...
```

alternative 2 (my preference when it works (e.g. when you want to exit early in a non-Ok case):

```rust
let Ok(contents) = std::fs::read_to_string(&rpc_config) else {
    ...
};
...
```

File: hyperdrive/src/register.rs [hunk 2]
```diff
@@ -245,38 +245,139 @@ pub async fn register(
...
+            );
         }
     }
 
+    // TODO: Remove debug logging before merging
+    eprintln!("[DEBUG-AUTH] ❌ All providers (configured + fallback) failed!");
+
     panic!(
-        "Error: runtime could not connect to Base ETH RPCs {rpc_urls:?}\n\
+        "Error: runtime could not connect to any ETH RPC providers\n\
```
Comment (nick1udwig) [inline hyperdrive/src/register.rs:378]: `Base` is significant here because we need the Base RPC to bootstrap our node. Would prefer this went back to `Base` from `any`

File: hyperdrive/src/register.rs [hunk 3]
```diff
@@ -245,38 +245,139 @@ pub async fn register(
...
         This is necessary in order to verify node identity onchain.\n\
-        Please make sure you are using a valid WebSockets URL if using \
-        the --rpc flag, and you are connected to the internet."
+        Please check your configured providers and internet connection."
```
Comment (nick1udwig) [inline hyperdrive/src/register.rs:380]: We now have 2 or 3 ways users can configure RPC so idk that it makes sense to list them all here. Maybe we should link to docs about how to set RPC?

I suppose this means deciding on and maintaining a canonical discussion somewhere. Two options I can think of are

https://book.hyperware.ai/kit/boot-real-node.html?highlight=rpc#--rpc
https://github.com/hyperware-ai/hyperdrive?tab=readme-ov-file#configuring-the-eth-rpc-provider

but it would ultimately be nice to give users as helpful an error message as possible.

**Review by nick1udwig — APPROVED** [review]
Style comment and a few nits. Correct the nits if you agree -- then feel free to merge after removing debugging stuff and confirming it still builds. Thanks for the nice work :rocket:

**Comment by dolled-possum** [comment]
All very good points!  Because they aren't critical, I'll merge this branch (which has pulled in Tobias' Z index work as well) and clean these up in the PR for Issue #729 which should be done later today.

File: hyperdrive/src/register.rs (hunk 2 above)
Comment (dolled-possum) [reply hyperdrive/src/register.rs:378]: There doesn't seem to be anything in the original code that limits the connections to Base eth RPCs, and my code maintains the status quo in the that regard.  I did update the message, but perhaps I should be enforcing some additional checks for chain ID 8453.  I'll look at that after the current work is done.

File: hyperdrive/src/register.rs (hunk 3 above)
Comment (dolled-possum) [reply hyperdrive/src/register.rs:380]: Created an issue to address this.

File: hyperdrive/src/main.rs (hunk 1 above)
Comment (dolled-possum) [reply hyperdrive/src/main.rs:170]: Updated, and because there were nested matches it avoided the dreaded quadruple indentation.
